
name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
    - develop
pr: none

resources:      
  repositories: 
  - repository: gx-devops-yamls
    name: gestionix/gx-devops-yamls
    type: github
    endpoint: gx-github
    ref: master #branch name

stages:
- stage: dev
  displayName: dev

  jobs:
  - job: Initial
    displayName: Initial
    steps:
    - template: /Common/keyvault.yaml
