
name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
    - develop
pr: none

resources:      
  repositories: 
  - repository: gx-devops-yamls
    name: gestionix/gx-devops-yamls
    type: github
    endpoint: gx-github
    ref: master #branch name

stages:
- stage: dev
  displayName: dev

  jobs:
  - job: Initial
    displayName: Initial
    steps:
    - task: AzureCLI@1
      displayName: Determining KeyVault
      inputs:
        azureSubscription: $(azureSubscriptionEndpoint)
        scriptLocation: inlineScript
        inlineScript: |
          ValueVault="$(Build.DefinitionName)-$(System.StageName)"
          KeyVault="$(az keyvault secret show --vault-name Eleva-Core-KeyVault --name $ValueVault --query value -o tsv)"
          echo "---$KeyVault----"
          echo "##vso[task.setvariable variable=Name;isOutput=true]$KeyVault"
      name: KeyVault
  
    - task: AzurePowerShell@4
      displayName: 'Get keys'
      inputs:
        azureSubscription: '$(azureSubscriptionEndpoint)'
        ScriptType: 'InlineScript'
        Inline: |
          $keys = (Get-AzKeyVaultSecret  -VaultName $(KeyVault.Name)).name 
          $key= $keys.Split(" ")
          $keyvalue= @{}
          foreach ($value in $key ){
              $secretstore=(Get-AzKeyVaultSecret  -VaultName $(KeyVault.Name) -name $value).SecretValueText
              $keystore=$value.Replace("-","_")
              Add-Content $(System.DefaultWorkingDirectory)/env.txt "$keystore=$secretstore"
          }
          get-content $(System.DefaultWorkingDirectory)/env.txt
          ((Get-Content -path $(System.DefaultWorkingDirectory)/kustomization.yaml) -replace 'KEYVAULT-SECRET',$(KeyVault.Name)) | Set-Content -Path $(System.DefaultWorkingDirectory)/kustomization.yaml
          ls
          pwd
        azurePowerShellVersion: 'LatestVersion'
        
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'Keleva'
        command: 'apply'
        arguments: '-k .'
