apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  # generate a Secret
- name: KEYVAULT-SECRET
- namespace: "boa-dev"
  # env is a path to a file to read lines of key=val
  # you can only specify one env file per secret.
  env: env.txt
  type: Opaque
generatorOptions:
  disableNameSuffixHash: true
