apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ .Values.appname }}"
  namespace: "{{ .Values.namespace }}-{{ .Values.stagename }}"
  labels:
    app: "{{ .Values.appname }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.appname }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.appname }}"
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      containers:
      - name: app
        image: "elevacontainerregistry.azurecr.io/{{ .Values.imagename }}:{{ .Values.imagetag }}"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: "{{ .Values.keyvault }}"
      imagePullSecrets:
      - name: elevacontainerregistry