apiVersion: apps/v1
kind: Deployment
metadata:
  name:  boa-ngin
  namespace: kv
  labels:
    app: boa-ngin
spec:
  selector:
    matchLabels:
      app: boa-ngin
  replicas: 1
  template:
    metadata:
      labels:
        app: boa-ngin
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      containers:
      - name: ngin
        image: nginx
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: kustomization
      imagePullSecrets:
      - name: elevacontainerregistry