apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appname }}-{{ .Values.stagename }}"
  namespace: "{{ .Values.namespace }}-{{ .Values.stagename }}"
spec:
  selector:
    app: "{{ .Values.appname }}" 
  ports:
  - port: 80
    targetPort: 80
