apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.appname }}-{{ .Values.stagename }}"
  namespace: "{{ .Values.namespace }}-{{ .Values.stagename }}"
spec:
  hosts:
  - 'work.eleva.inc'
  gateways:
  - eleva-reliability-room/https-work-eleva-gateway
  - mesh
  http:
  - name: 
    match:
    - headers: 
        back:
          exact: "{{ .Values.appname }}-{{ .Values.stagename }}"
    route:
    - destination:
        host: "{{ .Values.appname }}-{{ .Values.stagename }}"
        port:
          number: 80
